application: omdays
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: webapp/index.html
  upload: webapp/(.*\.html)
- url: /js
  static_dir: webapp/
- url: /out
  static_dir: webapp/out

- url: /.*
  script: _go_app